s = set()
# print(type(s))
# s_from_list = set([1, 2,3, 4, 5, 6,])
# print(s_from_list)
# print(type(s_from_list))
s.add(1)
s.add(2)
# s.remove(1)
s1 = s.union({1, 2, 3})
s2 = s.intersection({1, 2, 3, 4, 5})
print(s1)
print(s2)
print(s)
